-- ============================================================
-- Supabase 연동용 스키마 (PostgreSQL)
-- Supabase 대시보드 > SQL Editor 에서 전체 실행하세요.
-- ============================================================

-- 1) 회사 테이블 (관리자 > 등록된 회사)
CREATE TABLE IF NOT EXISTS public.companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    number TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2) 앱 사용자 테이블 (관리자 > 등록된 사용자, Auth와 별도)
CREATE TABLE IF NOT EXISTS public.app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    companies JSONB NOT NULL DEFAULT '[]',
    join_date TEXT,
    status TEXT NOT NULL DEFAULT '활성',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3) 프로필 테이블 (Auth 사용자용: 로그인 후 표시명·회사·관리자 여부)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    company_name TEXT,
    is_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_app_users_email ON public.app_users(email);
CREATE INDEX IF NOT EXISTS idx_companies_name ON public.companies(name);

-- RLS 활성화
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- companies: 인증된 사용자만 읽기/쓰기 (관리자 화면에서 사용)
CREATE POLICY "companies_select" ON public.companies
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "companies_insert" ON public.companies
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "companies_update" ON public.companies
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "companies_delete" ON public.companies
    FOR DELETE TO authenticated USING (true);

-- app_users: 인증된 사용자만 읽기/쓰기
CREATE POLICY "app_users_select" ON public.app_users
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "app_users_insert" ON public.app_users
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "app_users_update" ON public.app_users
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "app_users_delete" ON public.app_users
    FOR DELETE TO authenticated USING (true);

-- profiles: 본인만 읽기/수정, 가입 시 insert
CREATE POLICY "profiles_select_own" ON public.profiles
    FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles
    FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Auth 가입 시 프로필 자동 생성 (raw_user_meta_data 반영)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, company_name, is_admin)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'fullName', split_part(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data->>'company_name', NEW.raw_user_meta_data->>'companyName', ''),
        COALESCE((NEW.raw_user_meta_data->>'is_admin')::boolean, (NEW.raw_user_meta_data->>'isAdmin')::boolean, false)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- profiles updated_at 자동 갱신
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- (선택) 초기 데이터 삽입 - 관리자 화면과 맞추려면 아래 주석 해제 후 실행
/*
INSERT INTO public.companies (name, number) VALUES
    ('테크노바 주식회사', '123-45-67890'),
    ('미래산업 코퍼레이션', '987-65-43210'),
    ('글로벌테크 주식회사', '345-67-89012'),
    ('혁신솔루션즈', '456-78-90123'),
    ('디지털플러스', '567-89-01234')
ON CONFLICT DO NOTHING;

INSERT INTO public.app_users (name, email, companies, join_date, status) VALUES
    ('김철수', 'demo1@company.com', '["테크노바 주식회사", "글로벌테크 주식회사"]', '2025.12.01', '활성'),
    ('이영희', 'demo2@company.com', '["미래산업 코퍼레이션"]', '2025.12.15', '활성')
ON CONFLICT (email) DO NOTHING;
*/
